FORMAT: 1A
HOST: http://drunkcraft.crabdance.com:8085

# DrunkcraftHubApi

The API for the Drunkcraft Hub Site

## News Collection

## Get All News [/news]

This can be used to get all of the data from the news table.

### List All News Items [GET]

+ Response 200 (application/json)

        [
            {
                "id":1,
                "news_title":"test title",
                "news_text":"test text",
                "created_by":"test author",
                "updated_by": "update author",
                "createdAt":"2015-09-21T00:00:00.000Z",
                "updatedAt":"2015-09-21T00:00:00.000Z"
            }, {
                "id":2,
                "news_title":"test title 2",
                "news_text":"test text 2",
                "created_by":"test author",
                "updated_by": "update author",
                "createdAt":"2015-09-23T00:00:00.000Z",
                "updatedAt":"2015-09-23T00:00:00.000Z"
            }
        ]

## Get by News ID [/news/{id}]

### Get by News ID [GET]

+ Parameters
    + id: 1 (required, number) - ID of the News in form of an integer

+ Response 200 (application/json)

        {
            "id":1,
            "news_title":"test title",
            "news_text":"test text",
            "created_by":"test author",
            "updated_by": "update author",
            "createdAt":"2015-09-21T00:00:00.000Z",
            "updatedAt":"2015-09-21T00:00:00.000Z"
        }

## Get by News ID [/news/author/{author}]

### Get by News Author [GET]

+ Parameters
    + author: test author (required, number) - ID of the author in form of an integer

+ Response 200 (application/json)

        [
            {
                "id":1,
                "news_title":"test title",
                "news_text":"test text",
                "created_by":"test author",
                "updated_by": "update author",
                "createdAt":"2015-09-21T00:00:00.000Z",
                "updatedAt":"2015-09-21T00:00:00.000Z"
            }, {
                "id":2,
                "news_title":"test title 2",
                "news_text":"test text 2",
                "created_by":"test author",
                "updated_by": "update author",
                "createdAt":"2015-09-23T00:00:00.000Z",
                "updatedAt":"2015-09-23T00:00:00.000Z"
            }
        ]
